### ISSUE TITLE
Criar um canal de comunicação

### ISSUE THREAD

**Issue by gabisurita** [gabisurita/unicampi#25]
Criar um Slack, ou Telegram, ou lista de emails, ou canal no IRC, ou comunidade no Orkut pra gente se falar! =)

**Comment by fpg1503** [comment]
Acho que Slack ou [Gitter](https://gitter.im) são boas opções

**Comment by gabisurita** [comment]
Criei um slack!
https://unicampi-slack.herokuapp.com/
